[dev_front]
magnolia-dev-front ansible_host=magnolia.readresolve.tech ansible_port=50000 ansible_user=magnolia

[dev_back]
magnolia-dev-back ansible_host=magnolia.readresolve.tech ansible_port=50000 ansible_user=magnolia

[prod_front]
magnolia-prod-front ansible_host=magnolia.readresolve.tech ansible_port=50000 ansible_user=magnolia

[prod_back]
magnolia-prod-back ansible_host=magnolia.readresolve.tech ansible_port=50000 ansible_user=magnolia

[dev:children]
dev_front
dev_back

[prod:children]
prod_front
prod_back

[dev:vars]
target_env=DEV
front_deploy_dir=/srv/readresolve.tech/magnolia/www/a-deux-pas-dev
back_deploy_dir=/srv/readresolve.tech/magnolia/api/a-deux-pas-dev
front_http_url=https://magnolia.readresolve.tech/a-deux-pas-dev
back_api_url=https://magnolia.readresolve.tech/dev/api
back_internal_url=http://127.0.0.1:8901/api
front_version_url=https://magnolia.readresolve.tech/a-deux-pas-dev/assets/frontend-version.json
back_version_url=http://127.0.0.1:8901/backend-version.json
back_app_port=8901
http_auth_user=webuser
ansible_ssh_pass={{ lookup('env', 'SSH_PASSWORD') }}

[prod:vars]
target_env=PROD
front_deploy_dir=/srv/readresolve.tech/magnolia/www/a-deux-pas-prod
back_deploy_dir=/srv/readresolve.tech/magnolia/api/a-deux-pas-prod
front_http_url=https://magnolia.readresolve.tech/a-deux-pas-prod
back_api_url=https://magnolia.readresolve.tech/prod/api
back_internal_url=http://127.0.0.1:8902/api
front_version_url=https://magnolia.readresolve.tech/a-deux-pas-prod/assets/frontend-version.json
back_version_url=http://127.0.0.1:8902/backend-version.json
back_app_port=8902
http_auth_user=webuser
ansible_ssh_pass={{ lookup('env', 'SSH_PASSWORD') }}
